#============================================================================#
#                                                                            #
#                       Date Created: 19/09/2023                             #
#                     Author: Sacha Roussakis-Notter                         #
#                                                                            #
# ===========================================================================#

name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

pr: none

resources:
  repositories:
  - repository: DFW1N
    type: github
    name: DFW1N/SRE_Test
    endpoint: DFW1N

parameters:

- name: deployEnvironments
  displayName: Environments
  type: string
  default: "Development"
  values:
    - "Development"
    - "Sandbox"
    - "Non-Production"

- name: SelectPart
  displayName: Select Deployment Part
  type: string
  default: "Virtual Machine"
  values:
    - "Virtual Machine Web Server"
    - "Azure Kubernetes Cluster"

- name: DeploymentPlan
  displayName: Show Plan
  type: boolean
  default: True
  values:
    - False
    - True

- name: destroyEnvironment
  displayName: Destroy
  type: boolean
  default: False
  values:
    - False
    - True

  variables:

  - template: templates/variables/yaml_variables.yml
  parameters:
      deployEnvironments: ${{ parameters.deployEnvironments }}
      DeploymentPlan: ${{ parameters.DeploymentPlan }}
      destroyEnvironment: ${{ parameters.destroyEnvironment }}

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


