---
- name: Update NGINX Configuration
  hosts: your_azure_vm
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
    - name: Update NGINX Configuration
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^(\s*return 200 "Hello, World";\s*)$'
        line: '        return 200 "Hello, World Ansible!";'
      notify: Restart NGINX

  handlers:
    - name: Restart NGINX
      systemd:
        name: nginx
        state: restarted
