---
- name: Update Nginx HTML
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Install Nginx (if not already installed)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Update Nginx HTML file
      blockinfile:
        path: /var/www/html/index.html
        block: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Hello, World from Ansible</title>
          </head>
          <body>
            <h1>Hello, World from Ansible</h1>
          </body>
          </html>
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted