#============================================================================#
#                                                                            #
#                       Date Created: 19/09/2023                             #
#                     Author: Sacha Roussakis-Notter                         #
#                                                                            #
# ===========================================================================#

---
- name: Update Nginx HTML
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Install Nginx (if not already installed)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Clear existing content
      shell: echo -n > /var/www/html/index.html

    - name: Write new content to the file
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Hello, World from Ansible</title>
          </head>
          <body>
            <h1>Hello, World from Ansible</h1>
          </body>
          </html>
        dest: /var/www/html/index.html

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted