#============================================================================#
#                                                                            #
#                       Date Created: 19/09/2023                             #
#                     Author: Sacha Roussakis-Notter                         #
#                                                                            #
# ===========================================================================#

# This config file has been created so we can use YQ to set variables and pull them into the bash script without having to pass them as input parameters into the script.

Terraform:
  Backend:
    storage_account_name: 'example-storage-account-name'
    resource_group_name: 'example-resource-group-name'
    container_name: 'tfstate'
  Modules:
    Variables:
      Tags:
        managedBy: 'Sacha Roussakis-Notter' # <--- This is top level variables that will be passed to all modules from the shell script or pipeline.
    
