#cloud-config
packages:

write_files:
- path: /home/${user}/install_nginx.sh
  append: false
  content: ${install_agent_script_b64}
  encoding: b64

runcmd:
  - dos2unix /home/${user}/install_nginx.sh
  - sudo chmod +x /home/${user}/install_nginx.sh
  - sudo chown ${user}:${user} /home/${user}
  - sudo chown ${user}:${user} /home/${user}/install_nginx.sh
  - sudo -u ${user} /home/${user}/install_nginx.sh

final_message: "Installed Ngnix and Host a Hello, World! Web page, $UPTIME seconds into cloud-init"